AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'action_controller-twirp.gemspec'
    - 'vendor/bundle/**/*'
    - 'test/dummy/lib/user_pb.rb'
    - 'test/dummy/lib/user_twirp.rb'

Style/Documentation:
  Enabled: true
  Exclude:
    - 'test/**/*'

Style/IfUnlessModifier:
  Enabled: false

Metrics/ClassLength:
  Enabled: true
  Exclude:
    - 'test/**/*'
