AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'action_controller-twirp.gemspec'
    - 'vendor/bundle/**/*'

Style/Documentation:
  Enabled: true
  Exclude:
    - 'test/**/*'
