# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("user.proto", :syntax => :proto3) do
    add_message "example.v1.User" do
      optional :id, :int64, 1
      optional :name, :string, 2
    end
    add_message "example.v1.ListUsersRequest" do
    end
    add_message "example.v1.ListUsersResponse" do
      repeated :users, :message, 1, "example.v1.User"
    end
    add_message "example.v1.GetUserRequest" do
      optional :id, :int64, 1
    end
    add_message "example.v1.GetUserResponse" do
      optional :id, :int64, 1
    end
  end
end

module Example
  module V1
    User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("example.v1.User").msgclass
    ListUsersRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("example.v1.ListUsersRequest").msgclass
    ListUsersResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("example.v1.ListUsersResponse").msgclass
    GetUserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("example.v1.GetUserRequest").msgclass
    GetUserResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("example.v1.GetUserResponse").msgclass
  end
end
