# Code generated by protoc-gen-twirp_ruby 1.5.0, DO NOT EDIT.
require 'twirp'
require_relative 'user_pb.rb'

module Example
  module V1
    class UserApiService < Twirp::Service
      package 'example.v1'
      service 'UserApi'
      rpc :ListUsers, ListUsersRequest, ListUsersResponse, :ruby_method => :list_users
      rpc :GetUser, GetUserRequest, User, :ruby_method => :get_user
    end

    class UserApiClient < Twirp::Client
      client_for UserApiService
    end
  end
end
